- name: Restart openclaw gateway
  become: true
  become_user: moltron
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd.moltron[1] }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ ansible_facts.getent_passwd.moltron[1] }}/bus"
  ansible.builtin.systemd:
    name: openclaw-gateway.service
    scope: user
    state: restarted
